### ISSUE TITLE
duplicated hexcodes on the Dark Mode palette image

### ISSUE THREAD

**Issue by OniriCorpe** [Speyll/veqev#1]
hi!

the hexcodes in the Dark Mode palette image are mostly wrong
except the first 2 (`bg` & `fg`), they are duplicated on both lines

![The Dark Mode palette image](https://camo.githubusercontent.com/5226601ba2746b590ed8691dd5df402f0a8767df05f3775ca1ff014447ba5687/68747470733a2f2f692e6962622e636f2f677a673564794a2f76657165762d4461726b2e77656270)

**Comment by Speyll** [comment]
fixed ty!

**Comment by OniriCorpe** [comment]
You’re welcome! Thanks for your work
